name: angular_analyzer_plugin_example
description: Example app with not working analyzer plugin
version: 0.0.2
author: zmlcoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: '2.0.0-dev.31.0'

dependencies:
  angular: 5.0.0-alpha+6

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular:
    entry_points:
      - web/main.dart
- dart_to_js_script_rewriter